channels:
- conda-forge
dependencies:
- python=3.11.0
- pip<=25.2
- pip:
  - mlflow==3.4.0
  - cloudpickle==3.1.1
  - numpy==2.3.3
  - pandas==2.3.2
  - pyarrow==21.0.0
  - scikit-learn==1.7.2
  - scipy==1.16.2
name: mlflow-env
