name: ML Pipeline - Train, Test & Deploy

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # manual trigger

env:
  PYTHON_VERSION: '3.10'
  CI: true
  MLFLOW_TRACKING_URI: 'file:./mlruns'#${{ secrets.MLFLOW_TRACKING_URI }}

jobs:
  # 1️⃣ Code Quality
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black pylint
          pip install -r requirements.txt

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Run Black formatter check
        run: black --check .
        continue-on-error: true

      - name: Run Flake8
        run: flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics
        continue-on-error: true

  # 2️⃣ Unit Tests
  unit-tests:
    runs-on: ubuntu-latest
    needs: code-quality
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov
      - name: Run unit tests
        env:
          MLFLOW_TRACKING_URI: ${{ env.MLFLOW_TRACKING_URI }}
        run: pytest tests/ -v --cov=src --cov-report=xml
      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: unittests

  # 3️⃣ Model Training
  train-model:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Create directories for artifacts
        run: |
          mkdir -p models
          mkdir -p metrics
          mkdir -p mlruns
      - name: Train model
        env:
          MLFLOW_TRACKING_URI: ${{ env.MLFLOW_TRACKING_URI }}
        run: python -m src.train
      - name: Upload model artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-runs
          #trained-model
          path: |
            models/
            metrics/
          retention-days: 14

  # 4️⃣ Model Evaluation
  evaluate-model:
    runs-on: ubuntu-latest
    needs: train-model
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Download model artifacts
        uses: actions/download-artifact@v4
        with:
          name: mlflow-runs
          #trained-model
      - name: Run model evaluation tests
        env:
          MLFLOW_TRACKING_URI: ${{ env.MLFLOW_TRACKING_URI }}
        run: pytest tests/test_model_performance.py -v

  # 5️⃣ Model Deployment (only on main branch)
  deploy-model:
    runs-on: ubuntu-latest
    needs: evaluate-model
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: pip install -r requirements.txt mlflow
      - name: Download model artifacts
        uses: actions/download-artifact@v4
        with:
          name: trained-model
      - name: Deploy to MLflow Model Registry
        run: |
          python scripts/deploy_model.py || echo "Add your deploy logic here"
      - name: Tag deployment
        run: |
          git tag -a "model-v$(date +%Y%m%d-%H%M%S)" -m "Model deployment"
          git push origin --tags

  # 6️⃣ Notification
  notify:
    runs-on: ubuntu-latest
    needs: [train-model, evaluate-model, deploy-model]
    if: always()
    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "ML Pipeline Status: ${{ job.status }}"
          to: "yashrajsharma231195@gmail.com"
          from: "yashrajsharma231195@gmail.com"
          body: |
            ML Pipeline finished.

            ✅ Training stage:   ${{ needs.train-model.result }}
            ✅ Evaluation stage: ${{ needs.evaluate-model.result }}
            ✅ Deployment stage: ${{ needs.deploy-model.result }}

            Check GitHub Actions logs for full details.

        # 💬 Slack Notification
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
              "text": "🚀 *ML Pipeline - Titanic Project* finished!\n
              *Training:*   ${{ needs.train-model.result }}\n
              *Evaluation:* ${{ needs.evaluate-model.result }}\n
              *Deployment:* ${{ needs.deploy-model.result }}\n
              👉 <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View full logs>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}