channels:
- conda-forge
dependencies:
- python=3.11.0
- pip<=25.2
- pip:
  - mlflow==2.16.2
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - pandas==2.2.2
  - psutil==7.1.0
  - pyarrow==17.0.0
  - scikit-learn==1.7.2
  - scipy==1.16.2
name: mlflow-env
